<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>

    <groupId>com.jeimandei.imanuelbytes</groupId>
    <artifactId>church-platform</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <modules>
        <module>church-common</module>
        <module>church-gateway-service</module>
        <module>church-auth-service</module>
        <module>church-user-service</module>
        <module>church-cms-service</module>
        <module>church-event-service</module>
        <module>church-media-service</module>
        <module>church-interaction-service</module>
        <module>church-admin-service</module>
    </modules>
</project>
